### PR TITLE
Feature theme augmentation

### LINKED ISSUE #1874: Improve theme augmentation
In #1858, we have started to uncover a couple of improvement opportunities around how the theme's type can be extended. I would propose we update the approach to match the main repository.
If anyone is interested it's up for grab, it should be as easy as following https://github.com/mui-org/material-ui/pull/21279.

### PR DESCRIPTION
**Pull request by rajzik**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).

Fixes: #1874

This PR will unify the approach to the material-ui monorepo see: https://github.com/mui-org/material-ui/tree/next/packages/material-ui-lab/src/themeAugmentation

I also added documentation for the theme augmentation as well as fixed component names to correspond with theme overrides.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@rajzik Thanks for the effort. Note that we are working on merging the components into the lab in https://github.com/mui-org/core-plus-pickers. We will have to redo this pull request on https://github.com/mui-org/material-ui once the migration is completed.

**Comment by rajzik** [comment]
@oliviertassinari oh, nvm. If you need any help just let me know.

**Comment by oliviertassinari** [comment]
I will let you know :)

**Comment by rajzik** [comment]
@oliviertassinari is there any estimation when the migration will be done?

**Comment by oliviertassinari** [comment]
@dmtrKovalenko is making great progress. I think that so far, the main blocker is to reach a point where https://github.com/mui-org/core-plus-pickers/tree/next/packages/pickers is no longer included in the repository.

**Comment by oliviertassinari** [comment]
@rajzik Thanks for the effort! I believe we have solved the issue by moving the component in the lab.

**Pull request closed without merging**
