### PR TITLE
Export the default Toolbar components

### LINKED ISSUE #1694: Consider exposing the default toolbar implementations
I would like to extend the DateTimePickerToolbar through composition, so it would be useful to be able to import the [default implementation](https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/DateTimePicker/DateTimePickerToolbar.tsx).

### PR DESCRIPTION
**Pull request by Philipp91**
This PR closes #1694

### CODE REVIEW

**Review by dmtrKovalenko — APPROVED** [review]

**Review by oliviertassinari — COMMENTED** [review]
The change seems to make 4 new components to include in item 1 of #1604, is this accurate? Should we add the forwardRef now, while we are at it?

**Comment by oliviertassinari** [comment]
This one is also interesting, the name of the stylesheet doesn't match the name of the component:

https://github.com/mui-org/material-ui-pickers/blob/7bed283699ef768936a3ec7c5dc89571492dddd4/lib/src/DateTimePicker/DateTimePickerToolbar.tsx#L37

I think that we should update it.

Actually, given that the style sheet is public (`Mui` prefix, not `Private`) making the component public too makes sense.

**Comment by Philipp91** [comment]
> The change seems to make 4 new components to include in item 1 of #1604, is this accurate? Should we add the forwardRef now, while we are at it?

I'd do that in a separate commit/PR anyway, as it's a separate concern. Personally I have 0 knowedge about refs, I don't use them in my application.

> the name of the stylesheet doesn't match the name of the component. I think that we should update it.

Good point. Actually, they're currently called: `MuiPickersDatePickerRoot`, `MuiPickersTimePickerToolbar`, `MuiPickerDTToolbar` and `MuiPickersDatePickerRoot` (for the range picker). The latter obviously lacks a "Range" in the middle. But also, is the correct prefix "MuiPicker" or "MuiPickers"? And is the correct suffix "Root" or "Toolbar"?

**Comment by oliviertassinari** [comment]
> I'd do that in a separate commit/PR anyway, as it's a separate concern. Personally I have 0 knowedge about refs, I don't use them in my application.

@Philipp91 I think that we would want to handle it here, if we want to make the components public, we might as well have it following the standard.

Regarding the name of the style sheets, they should be identical to the name of the exposed components. Does it answer the problem?

**Review by dmtrKovalenko — CHANGES_REQUESTED** [review]
I think that we should 
1. handle the public ref
2. handle the public class names

**Comment by Philipp91** [comment]
> I think that we should
> 
> 1. handle the public ref

I tried, but like I said I have too little experience with refs (and I guess material-ui's TypeScript types in this case) to figure it out. Here's my current attempt: https://github.com/Philipp91/material-ui-pickers/commit/29f16c2029063d79b9accfdd51f38b9acd42f5d8

It throws a long error message on the `<Toolbar` line, which I believe boils down to
```
Type 'HTMLDivElement' is not assignable to type 'CommonProps<ToolbarTypeMap<{}, "div">>'. 
  The types of 'style.backfaceVisibility' are incompatible between these types. 
  Type 'string' is not assignable to type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "hidden" | "visible" | undefined'.
```

> 2. handle the public class names

By that, did you mean the styles overrides? (See https://github.com/mui-org/material-ui-pickers/pull/1736) If not, what else do you mean by class names?

**Comment by oliviertassinari** [comment]
> By that, did you mean the styles overrides? (See #1736) If not, what else do you mean by class names?

Great, thanks for initiating this effort

**Review by dmtrKovalenko — APPROVED** [review]

**Pull request merged**
