### PR TITLE
[core] Align internal icons with mono-repository

### PR DESCRIPTION
**Pull request by oliviertassinari**
- Remove redundant `Icon` suffix
- Use import *
- Label as internal, a deterrent for developers to import these icons
- Remove useless paths

### CODE REVIEW

**Review by dmtrKovalenko — CHANGES_REQUESTED** [review]
I'd like not to move to default exports of `React` at least for now. 
And also interesting why visual regression didn't start? Probably because this is a forked branch. Need to investigate – I'd like to see what's changed after deleting paths from SVG.

**Comment by oliviertassinari** [comment]
What's the concern with the import, it seems we do it most of the time already? 
https://github.com/mui-org/material-ui-pickers/blob/0d41c48aaa8b9b6f67e72deee9583340cd218b89/lib/src/views/Clock/ClockNumber.tsx#L1

**Comment by dmtrKovalenko** [comment]
image

But it is there ...
image

**Comment by dmtrKovalenko** [comment]
@oliviertassinari  Sorry I am blind. For some reason I thought you moved `*as` to default. It is ok – thanks... my bad XD 

> Its left to figure out what's wrong with visual regression. It's for me probably

**Review by dmtrKovalenko — APPROVED** [review]

**Pull request merged**
