### PR TITLE
Add showLeftArrowButton and showRightArrowButton props to CalendarHeader

### PR DESCRIPTION
**Pull request by PickleyD**
Add ability to hide left and right arrow buttons in calendar header. Useful if you want to control the calendar externally.

Still needs tests writing but is this feature something that would be considered?

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Why not to make them just disabled? Why not just do `leftArrowButtonProps={{ hidden: true }}`?

**Comment by PickleyD** [comment]
Am I wrong in thinking that the props must match those specified here: https://material-ui.com/api/icon-button/ ?

**Comment by dmtrKovalenko** [comment]
I mean that your case is really rare. It will be easier for you and for us just to hide your buttons with css. 
`leftArrowButtonProps={{ disabled: true, style: { visibility: 'hidden' }}}` Or pass classname that will hide the button, or anything

**Comment by PickleyD** [comment]
Understood. You're right. Thanks for your help!

On a related note. Here's something that originally gave me unexpected results...
Currently the props are in this order: 

```
{...leftArrowButtonProps}
disabled={isPreviousMonthDisabled}
```
which means that any `disabled` prop you pass in may be overridden by the `isPreviousMonthDisabled` / `isNextMonthDisabled` props. Is this intentional behaviour or should their order be swapped?

**Comment by dmtrKovalenko** [comment]
Yes, to prevent unexpected behavior of opening a month with all days disabled

**Pull request closed without merging**
