### PR TITLE
[docs] Use 3001 over 3000 to avoid conflict

### PR DESCRIPTION
**Pull request by oliviertassinari**
Allows running the mono-repository with the picker docs in dev mode at the same time.

### CODE REVIEW

**Review by dmtrKovalenko — APPROVED** [review]

**Comment by oliviertassinari** [comment]
I could reproduce the same fails on the next branch: https://github.com/mui-org/material-ui-pickers/commits/next.

**Comment by dmtrKovalenko** [comment]
Yeah, I’ll take a look on them tomorrow. Sorry

**Comment by oliviertassinari** [comment]
the next branch is green, I'm gonna assume it's safe to merge on Monday 😆.

**Comment by dmtrKovalenko** [comment]
Ohh yes, some of our tests depends on the time of year

**Pull request merged**
