### PR TITLE
[core] Allow a broader set of node.js versions

### PR DESCRIPTION
**Pull request by oliviertassinari**
- Solve `error: The engine "node" is incompatible with this module. Expected version "12.x". Got "13.8.0"`
- Match the strategy of the core, ease the future merge of the repositories

### CODE REVIEW

**Review by dmtrKovalenko — APPROVED** [review]
Yeah, that’s look more proper

**Comment by dmtrKovalenko** [comment]
Definitely weird that tests are failing. I can take a look on them tomorrow

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Something is "unstable" in the CI.
I have rerun the workflow on the latest commit of the "next" branch, the build went from green to red, with the same errors:

Capture d’écran 2020-03-18 à 21 13 10

**Comment by dmtrKovalenko** [comment]
It is very likely an edge case with daylight saving time change. 
I saw this thing a year ago I suppose XD

**Comment by oliviertassinari** [comment]
🤣 maybe we should freeze the date in the test, unless it would hide a core issue.

**Pull request merged**
