### PR TITLE
[WIP] Cypress coverage

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
Try to collect coverage from cypress tests

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@dmtrKovalenko What's the objective of this pull request? What's the status of it?

**Comment by dmtrKovalenko** [comment]
Can be closed, anyway will be supressed by other PR

**Comment by oliviertassinari** [comment]
@dmtrKovalenko It seems that the objective is to get test coverage reporting. If it's the case, we can defer the resolution of the problem to https://github.com/mui-org/material-ui/issues/19706, where it's already set up in the main repository. Is that correct?

**Comment by dmtrKovalenko** [comment]
No, I intend to keep cypress tests so it needs to be done anyway.
> It will be much easier after migrating all tests to components

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Would you mind expanding? From https://github.com/mui-org/material-ui-pickers/pull/1730#discussion_r419114709, I thought that the policy was to replace cypress with testing-library, and introduce it back or an alternative tool like [playwright](https://github.com/mui-org/material-ui/pull/21449) as we hit a roadblock (depending on the pain points and what can best solve it). In such a roadmap, coverage with cypress has little value.

**Comment by dmtrKovalenko** [comment]
Haha, I had absolutely different view

**Comment by oliviertassinari** [comment]
@dmtrKovalenko What do you think about it?

**Pull request closed without merging**
