### PR TITLE
test: add dayjs

### PR DESCRIPTION
**Pull request by PaulSavignano**
Add dayjs to ci tests

### CODE REVIEW

**Review by dmtrKovalenko — APPROVED** [review]

**Review by oliviertassinari — COMMENTED** [review]
Is this enough? What about the configuration of the CI in https://github.com/mui-org/material-ui-pickers/blob/0818b5eeffd9b1a8d80ac7ab6afa14151a92efeb/.circleci/config.yml#L150?

**Comment by dmtrKovalenko** [comment]
Ohh, I think it was only about an ability to run dayjs tests. 
On CI definitely we need to add one new workflow step

**Comment by oliviertassinari** [comment]
Ok, so the question is, should we run dayjs in the CI too?

**Comment by oliviertassinari** [comment]
> should we run dayjs in the CI too?

I assume that the answer is yes.

**Comment by PaulSavignano** [comment]
Sounds good.  I'll add it to the ci.

**Pull request merged**
