### PR TITLE
Fix incorrect prop type on `children`

### LINKED ISSUE #1360: Invalid prop `children` supplied to `LocalizationProvider`
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.7 |
| material-ui          | 4.4.3  |
| React                | 16.10.1 |
| Browser              | Firefox 69.0.3|
| Peer library         | moment |

## Steps to reproduce

1. Render
```
      <MuiPickersUtilsProvider libInstance={moment} utils={MomentUtils}>
        <h1>Component</h1>
        <p>More than one sub component</p>
      </MuiPickersUtilsProvider >
```

## Expected behavior

No warning, renders both sub components

## Actual behavior

Renders both sub components, but browser console says:

    Warning: Failed prop type: Invalid prop `children` supplied to `MuiPickersUtilsProvider`.
    in MuiPickersUtilsProvider (created by MyParentComponent)
    in ...

## Workaround
Wrap the sub components in a `React.Fragment`
```
      <MuiPickersUtilsProvider libInstance={moment} utils={MomentUtils}>
        <>
          <h1>Component</h1>
          <p>More than one sub component</p>
        </>
      </MuiPickersUtilsProvider >
```

### PR DESCRIPTION
**Pull request by vdh**
This PR closes #1360

## Description
Fix for incorrect prop type on `children`

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
We are moved to `LocalizationProvider`. I don’t know why `MuiUtilaProvider` is still here

**Review by dmtrKovalenko — DISMISSED** [review]
Please move changes to `LocalizationProvider`

**Comment by vdh** [comment]
@dmtrKovalenko This is a v3.2 bug that has been sitting around since October. There was [a comment](https://github.com/mui-org/material-ui-pickers/issues/1360#issuecomment-573436467) about fixing it but it was never implemented.

Or have v3.2 bugs been kicked to the curb…?

**Comment by oliviertassinari** [comment]
I would encourage declining all pull request to the v3 branch unless there is a major issue or a security concern. We have limited resources, I think that it's better to invest them for the future version.

:+1: for rebasing on the `next` branch.

**Review by oliviertassinari — APPROVED** [review]

**Review by dmtrKovalenko — APPROVED** [review]

**Pull request merged**
