### PR TITLE
Fix core@v4.9.9 support with createSvgIcon

### LINKED ISSUE #1619: createSvgIcon refactor in @material-ui 4.9.9 breaking builds
| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   v4.0.0-alpha.4   |
| material-ui          |  v4.9.9       |

## Expected behavior

Use createSvgIcon from utils export

`import { createSvgIcon } from '@material-ui/core/utils';`

instead of 

`import createSvgIcon from '@material-ui/core/internal/svg-icons/createSvgIcon';`

@ https://github.com/mui-org/material-ui-pickers/blob/574944acbb6e3918803914078674d9d815fc260c/lib/src/_shared/icons/ArrowDropDownIcon.tsx#L2

## Actual behavior

```
Module not found: Can't resolve '@material-ui/core/internal/svg-icons/createSvgIcon' in '/.../node_modules/@material-ui/pickers'
```

Refactored utility `createSvgIcon` in latest material-ui version breaks pickers svgs. This has been removed from the internal path in the following commit

https://github.com/mui-org/material-ui/commit/8ea2df8a18fb4a1f8a89e755e0d7f05a9b8eed73

### PR DESCRIPTION
**Pull request by Vincz**
Update import of `createSvgIcon` according to closes #1619.

### CODE REVIEW

**Review by dmtrKovalenko — APPROVED** [review]

**Comment by dmtrKovalenko** [comment]
Missed global module name in rollup config. But everything else looks good

**Comment by Vincz** [comment]
Thx for the quick review @dmtrKovalenko !

I'm not sure about this two files:
`material-ui-pickers/lib/rollup.config.js`

and

`material-ui-pickers/lib/typings.d.ts`

Can you help me?
Thanks!

**Comment by dmtrKovalenko** [comment]
In typings — remove our overrides. 
In rollup config — add to globals:
```
‘{new import path}’: materialUi.utils
````

**Review by dmtrKovalenko — APPROVED** [review]

**Comment by Vincz** [comment]
Awesome ! Thx @oliviertassinari & @dmtrKovalenko !
Is it possible to publish the updated version on npm ? 
Thanks!

**Comment by dmtrKovalenko** [comment]
Yeah, will publish it asap. Probably tomorrow.

**Pull request merged**
