### PR TITLE
Require Material-UI v5 alpha

### PR DESCRIPTION
**Pull request by eps1lon**
Getting an overview...

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]

**Comment by oliviertassinari** [comment]
We might want to update 

https://github.com/mui-org/material-ui-pickers/blob/ff3368340301d8e16b9b42781b6d02487ca07fc0/lib/package.json#L3

to 

```
5.0.0-alpha.11
```

**Comment by eps1lon** [comment]
I wouldn't skip a version. That is always confusing.

**Comment by oliviertassinari** [comment]
Ok, fair enough

**Comment by oliviertassinari** [comment]
Released as v4.0.0-alpha.11

**Pull request merged**
